name: _aneris
channels:
  - defaults
  - conda-forge
  - dataonlygreater
dependencies:
  - python=2.7
  - pip
  - attrdict
  - numpy
  - openpyxl
  - pandas >=0.20
  - pywin32
  - pyyaml
  - sqlalchemy
  - xlrd
  - xlwt
